apiVersion: v1
kind: Service
metadata:
  labels:
    service: uda-connectionservice
  name: uda-connectionservice
spec:
  ports:
  - name: "50056"
    port: 50056
    targetPort: 50056
    nodePort: 30002
  selector:
    service: uda-connectionservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-connectionservice
  name: uda-connectionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uda-connectionservice
  template:
    metadata:
      labels:
        service: uda-connectionservice
    spec:
      containers:
      - image: nat389/uda-connectionservice:latest
        name: uda-connectionservice
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVICE
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVICE
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_PORT
        