apiVersion: v1
kind: Service
metadata:
  labels:
    service: uda-personservice
  name: uda-personservice
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: uda-personservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-personservice
  name: uda-personservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uda-personservice
  template:
    metadata:
      labels:
        service: uda-personservice
    spec:
      containers:
      - image: nat389/uda-personservice:latest
        name: uda-personservice
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
